name: Pull Request

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout do repositorio
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '14'
            
            - name: Instalando dependencias
              run: npm install

            - name: Run tests
              run: npm test

            - name: Analise do code
              uses: action/checkout@v2
              with:
                repository: ${{ github.repository }}
                ref: ${{ github.head_ref }}
                path: ./code
            - name: Analisar code
              uses: github/codeql-action/analyze@v1
              with:
                languages: javascript
                queries: ./code

            - name: Report results
              run: echo "A construção e análise foram concluidas com sucesso!"
