name: Pull Request

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Instalando dependências
        run: npm install

      - name: Rodar testes
        run: npm test

      - name: Inicializar CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript

      - name: Análise de código com CodeQL
        uses: github/codeql-action/analyze@v1

      - name: Reportar resultados
        run: echo "A construção e análise foram concluídas com sucesso!"
